import { dump as dumpYaml } from "js-yaml";
import type { GlobalConfig, RepoEntry } from "../config.js";

export interface GitHubUser {
  login: string;
  id: number;
  name: string | null;
}

export interface ListedRepo {
  nameWithOwner: string;
  isPrivate: boolean;
  description: string | null;
}

/** GitHub's private noreply address that still attributes commits to the user. */
export function noreplyEmail(user: Pick<GitHubUser, "id" | "login">): string {
  return `${user.id}+${user.login}@users.noreply.github.com`;
}

export function defaultGitAuthor(user: GitHubUser): string {
  return user.name?.trim() || user.login;
}

/** Production-sane defaults written by onboarding (not the local test overrides). */
export function defaultOnboardConfig(identity: {
  gitAuthor: string;
  gitEmail: string;
}): GlobalConfig {
  return {
    runProbability: 0.35,
    quietHours: [0, 1, 2, 3, 4, 5],
    maxActionsPerDay: 2,
    actionWeights: {
      commit: 3,
      pull_request: 2,
      review: 2,
      issue: 1,
      noop: 4,
    },
    safePaths: ["docs/**", "*.md", "CHANGELOG.md", ".github/**"],
    cooldownHours: 20,
    gitAuthor: identity.gitAuthor,
    gitEmail: identity.gitEmail,
  };
}

export function buildRepoEntries(repoNames: string[]): RepoEntry[] {
  return repoNames.map((repo) => ({
    repo,
    actions: {
      commit: true,
      pull_request: true,
      review: true,
      issue: true,
    },
    safePaths: ["docs/**", "*.md", "CHANGELOG.md"],
  }));
}

export function renderConfigYaml(config: GlobalConfig): string {
  const header = `# Global settings for daily-commit. Per-repo overrides live in repos.yml.
# Generated by \`dc onboard\`.

`;
  return header + dumpYaml(config, { lineWidth: 100, noRefs: true });
}

export function renderReposYaml(repos: RepoEntry[]): string {
  const header = `# Target repositories daily-commit may act on.
# Generated by \`dc onboard\`.
# Your \`gh\` login (or GH_TOKEN) must have contents/pull-requests/issues write
# access to every repo listed here.

`;
  return (
    header +
    dumpYaml(
      {
        repos: repos.map((r) => ({
          repo: r.repo,
          actions: r.actions,
          ...(r.safePaths ? { safePaths: r.safePaths } : {}),
          ...(r.verifyCommand ? { verifyCommand: r.verifyCommand } : {}),
        })),
      },
      { lineWidth: 100, noRefs: true },
    )
  );
}
