import type { RepoEntry } from "../config.js";
import { runOutdatedDepsCheck } from "../detectors/outdatedDeps.js";
import { runTodoSweep } from "../detectors/todoSweep.js";
import { createIssue, listOpenIssueTitles } from "../gh.js";
import { pick } from "../random.js";
import { issueIntro, today } from "../templates/text.js";
import type { Workspace } from "../workspace.js";

export interface IssueOutcome {
  performed: boolean;
  reason?: string;
  url?: string;
  dryRun?: boolean;
  title?: string;
  body?: string;
}

const TODO_ISSUE_TITLE = "[dc] TODO/FIXME sweep";
const DEPS_ISSUE_TITLE = "[dc] Outdated dependency report";

async function buildTodoIssue(ws: Workspace): Promise<{ title: string; body: string } | null> {
  const result = await runTodoSweep(ws.dir);
  if (result.count === 0) return null;

  const sampleLines = result.sample
    .map((hit) => `- \`${hit.file}:${hit.line}\` — ${hit.text}`)
    .join("\n");

  return {
    title: TODO_ISSUE_TITLE,
    body: `${issueIntro()}\n\nFound **${result.count}** TODO/FIXME comment(s) in tracked files as of ${today()}. Sample:\n\n${sampleLines}\n\nThis is a plain \`git grep\` scan — no judgment on priority, just a pointer.`,
  };
}

async function buildDepsIssue(ws: Workspace): Promise<{ title: string; body: string } | null> {
  const result = await runOutdatedDepsCheck(ws.dir);
  if (!result.applicable || result.packages.length === 0) return null;

  const rows = result.packages
    .map((p) => `| \`${p.name}\` | ${p.current} | ${p.wanted} | ${p.latest} |`)
    .join("\n");

  return {
    title: DEPS_ISSUE_TITLE,
    body: `${issueIntro()}\n\n\`npm outdated\` results as of ${today()}:\n\n| package | current | wanted | latest |\n|---|---|---|---|\n${rows}\n\nGenerated by \`npm outdated --json\`, no other analysis applied.`,
  };
}

export async function runIssueAction(
  ws: Workspace,
  repo: RepoEntry,
  dryRun = false,
): Promise<IssueOutcome> {
  const builders = [buildTodoIssue, buildDepsIssue];
  const chosen = pick(builders);
  const issue = await chosen(ws);

  if (!issue) {
    return { performed: false, reason: "detector found nothing to report" };
  }

  const openTitles = await listOpenIssueTitles(repo.repo);
  if (openTitles.includes(issue.title)) {
    return { performed: false, reason: `an open issue titled "${issue.title}" already exists` };
  }

  if (dryRun) {
    return { performed: true, dryRun: true, title: issue.title, body: issue.body };
  }

  const url = await createIssue(repo.repo, {
    title: issue.title,
    body: issue.body,
    labels: ["housekeeping"],
  });

  return { performed: true, url, title: issue.title, body: issue.body };
}
